(defvar *robot* (jnew (jclass "java.awt.Robot")))
(defvar *delay-time* 1000)

(defun delay (ms)
	(jcall "delay" *robot* ms))

(defun lookup-key (keycode)
	(jfield "java.awt.event.KeyEvent" keycode))

(defun press-key (key)
	(jcall "keyPress" *robot* key))

(defun lookup-and-press-key (keycode)
	(press-key (lookup-key keycode)))

(defun main ()
	(print "inicializando...")
	(delay *delay-time*)
	(lookup-and-press-key "VK_M")
	(lookup-and-press-key "VK_E")
	(lookup-and-press-key "VK_U")
	(lookup-and-press-key "VK_SPACE")
	(lookup-and-press-key "VK_N")
	(lookup-and-press-key "VK_O")
	(lookup-and-press-key "VK_M")
	(lookup-and-press-key "VK_E")
	(lookup-and-press-key "VK_SPACE")
	(lookup-and-press-key "VK_E")
	(lookup-and-press-key "VK_SPACE")
	(lookup-and-press-key "VK_L")
	(lookup-and-press-key "VK_U")
	(lookup-and-press-key "VK_C")
	(lookup-and-press-key "VK_A")
	(lookup-and-press-key "VK_S"))
