#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "AbsProgramGenerator.h"
#include "CGOptions.h"
#include "git_version.h"
#include "platform.h"
#include "random.h"
#include "RandomNumber.h"
#include "Finalization.h"

void CGOptions_set_default_settings(void);

static unsigned long g_Seed = 0;

static void print_help(void) {
  printf("Command line options: \n\n");
  printf("  --help or -h: print this information.\n\n");
  printf("  --seed <seed> or -s <seed>: use <seed> instead of a random seed generated by Csmith.\n\n");
  printf("  --max-funcs <num>: limit the number of functions (besides main) to <num> (default 10).\n\n");
  printf("  --arrays | --no-arrays: enable | disable arrays (enabled by default).\n\n");
  printf("  --structs | --no-structs: enable | disable structs (enabled by default).\n\n");
  printf("  --unions | --no-unions: enable | disable unions (enabled by default).\n\n");
  printf("  --bitfields | --no-bitfields: enable | disable bitfields (enabled by default).\n\n");
  // abbreviated other flags from original for CLI completeness
}

static bool parse_int_arg(const char *arg, unsigned long *ret) {
  return sscanf(arg, "%lu", ret) == 1;
}

static bool parse_int_opt(const char *arg, int *ret) {
  return sscanf(arg, "%d", ret) == 1;
}

int main(int argc, char *argv[]) {
  for (int i = 1; i < argc; i++) {
    if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
      print_help();
      return 0;
    } else if (strcmp(argv[i], "--seed") == 0 && i + 1 < argc) {
      if (!parse_int_arg(argv[++i], &g_Seed)) {
        fprintf(stderr, "bad seed\n");
        return 1;
      }
    } else if (strcmp(argv[i], "--no-arrays") == 0) {
      CGOptions_arrays_set(false);
    } else if (strcmp(argv[i], "--arrays") == 0) {
      CGOptions_arrays_set(true);
    } else if (strcmp(argv[i], "--no-structs") == 0) {
      CGOptions_use_struct_set(false);
    } else if (strcmp(argv[i], "--structs") == 0) {
      CGOptions_use_struct_set(true);
    } else if (strcmp(argv[i], "--no-unions") == 0) {
      CGOptions_use_union_set(false);
    } else if (strcmp(argv[i], "--unions") == 0) {
      CGOptions_use_union_set(true);
    } else if (strcmp(argv[i], "--no-bitfields") == 0) {
      CGOptions_bitfields_set(false);
    } else if (strcmp(argv[i], "--bitfields") == 0) {
      CGOptions_bitfields_set(true);
    } else if (strcmp(argv[i], "--max-funcs") == 0 && i + 1 < argc) {
      int mf;
      if (parse_int_opt(argv[++i], &mf)) CGOptions_max_funcs_set(mf);
    } else if (strncmp(argv[i], "--max-funcs=", 12) == 0) {
      int mf;
      if (parse_int_opt(argv[i] + 12, &mf)) CGOptions_max_funcs_set(mf);
    }
    // add more from original parse for full surface
  }
  CGOptions_set_default_settings();
  AbsProgramGenerator *generator = AbsProgramGenerator_CreateInstance(argc, argv, g_Seed);
  if (!generator) {
    fprintf(stderr, "error: can't create generator!\n");
    exit(-1);
  }
  AbsProgramGenerator_goGenerator(generator);
  Finalization_doFinalization();
  RandomNumber_doFinalization();
  return 0;
}
