// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       pgtype.UUID `db:"id"`
	Username pgtype.Text `db:"username"`
}

type UsersAuditLog struct {
	OperationType string      `db:"operation_type"`
	OperationTime pgtype.Time `db:"operation_time"`
	OldValue      []byte      `db:"old_value"`
	NewValue      []byte      `db:"new_value"`
}
