[tools]
dbmate = "latest"
"github:golang-migrate/migrate" = "latest"
"github:sqlc-dev/sqlc" = "latest"
go = "latest"

[env]
DATABASE_URL = "postgres://admin:admin@localhost:5432/admin?sslmode=disable"

[tasks."codegen:queries"]
run = "sqlc generate"

[tasks.codegen]
depends = ["codegen:*"]

[tasks.new_migration]
run = "dbmate new {{option(name=\"name\", required=True)}}"

# [tasks."devdb:migrate"]
# run = "atlas migrate apply --url 'postgres://admin:admin@localhost:5432/admin?sslmode=disable' --dir file://db/migrations"

[tasks."devdb:up"]
run = " docker run --rm -e POSTGRES_PASSWORD=admin -e POSTGRES_USER=admin -e POSTGRES_DATABASE=admin -d -p 5432:5432 postgres"

[tasks."dev"]
run = "go run main.go"

[tasks."test:insert-user"]
run = "curl http://localhost:5090/create-user -F name={{option(name=\"user\", required=True)}}"
