/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biglucas.chat.ui;

import biglucas.chat.rmi.IChat;
import biglucas.chat.rmi.IChatCallback;
import biglucas.chat.rmi.exceptions.WhatsUTForbiddenActionException;
import biglucas.chat.server.Message;
import biglucas.chat.utils.MessageSubscriberProxy;
import biglucas.chat.utils.OnMessage;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lucasew
 */
public class ChatView extends javax.swing.JFrame implements Runnable {
    private IChat chat;
    private boolean over;
    
    public void dispose() {
        super.dispose();
        over = true;
    }
    public void run() {
        System.out.println("iniciada thread");
        while(!this.over) {
            StringBuilder builder = new StringBuilder();
            try {
                try {
                    System.out.println("Buscando mensagens");
                    Message[] messages = this.chat.getMessages();
                    System.out.printf("%d mensagens", messages.length);
                    for (Message message : messages) {
                        builder = builder
                                .append("<")
                                .append(message.sender)
                                .append("> ")
                                .append(message.text)
                                .append("\n");
                    }
                    this.canvas.setText(builder.toString());
                } catch (RemoteException e) {
                    e.printStackTrace();
                    Thread.sleep(100);
                    continue;
                } catch (WhatsUTForbiddenActionException ex) {
                    builder = builder.append("Acesso negado");
                    this.canvas.setText(builder.toString());
                }
                Thread.sleep(500);
            } catch (InterruptedException e) {
                break;
            }
        }
    }
    /**
     * Creates new form ChatView
     */
    public ChatView(IChat chat, String title) {
        this.chat = chat;
        this.over = false;
        initComponents();
        this.title.setText(title);
        new Thread(this).start();
    }
    
    
    public void onMessage(Message message) {
        System.out.println(message);
        this.canvas.append(String.format("<%s> %s\n", message.sender, message.text));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        canvas = new javax.swing.JTextArea();
        message = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        title.setText("Chat");

        canvas.setEditable(false);
        canvas.setColumns(20);
        canvas.setRows(5);
        jScrollPane1.setViewportView(canvas);

        send.setText("Enviar");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        close.setText("X");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(111, 111, 111)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(message)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(close))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        try {
            this.chat.sendMessage(message.getText());
            System.out.println("enviada mensagem");
        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(this, "O console tem mais detalhes", "Remote Exception", JOptionPane.ERROR_MESSAGE);
        } catch (WhatsUTForbiddenActionException e) {
            JOptionPane.showMessageDialog(this, "Vocẽ não tem permissão para fazer isso", "Acesso negado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sendActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea canvas;
    private javax.swing.JButton close;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField message;
    private javax.swing.JButton send;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
