FROM golang:1.21 AS build

WORKDIR /usr/src/app

COPY server_go/go.mod server_go/go.sum ./
RUN go mod download && go mod verify
COPY server_go/main.go ./
RUN go build -v -o server ./...

ENTRYPOINT ["/usr/src/app/server"]
# FROM scratch
# COPY --from=build /usr/src/app/server /

