services:
  loadbalancer:
    image: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
  db:
    image: lucasew/rinha202401-tigerbeetle-db
    build:
      dockerfile: ./Dockerfile.tigerbeetle
    deploy:
      # resources:
      #   limits:
      #     memory: 1024M
    volumes:
    - ./data:/data
  backend1:
    image: lucasew/rinha202401-backend
    restart: always
    environment:
      - "TB_ADDRESS=db:3000"
      - "GOMEMLIMIT=80MiB"
    build:
      dockerfile: ./Dockerfile.go-backend
  backend2:
    image: lucasew/rinha202401-backend
    restart: always
    environment:
      - "TB_ADDRESS=db:3000"
      - "GOMEMLIMIT=80MiB"
    build:
      dockerfile: ./Dockerfile.go-backend
