services:
  db:
    image: lucasew/rinha202401-tigerbeetle
    build:
      dockerfile: ./Dockerfile.tigerbeetle-lowram
    entrypoint: /tigerbeetle-start.sh
    # deploy:
      # resources:
      #   limits:
      #     memory: 1024M
    volumes:
    - ./data:/data
    - ./tigerbeetle-start.sh:/tigerbeetle-start.sh
  backend1:
    image: lucasew/rinha202401-backend
    restart: always
    environment:
      - "TB_ADDRESS=db:3000"
      - "GOMEMLIMIT=80MiB"
    build:
      dockerfile: ./Dockerfile.go-backend
    depends_on:
      - db
  backend2:
    image: lucasew/rinha202401-backend
    restart: always
    environment:
      - "TB_ADDRESS=db:3000"
      - "GOMEMLIMIT=80MiB"
    build:
      dockerfile: ./Dockerfile.go-backend
    depends_on:
      - db
