services:
  loadbalancer:
    image: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
  db:
    image: ghcr.io/lucasew/playground-rinha202401-tigerbeetle
    build:
      dockerfile: ./Dockerfile.tigerbeetle-lowram
    entrypoint: /tigerbeetle-start.sh
    # deploy:
      # resources:
      #   limits:
      #     memory: 1024M
    volumes:
    - ./data:/data
    - ./tigerbeetle-start.sh:/tigerbeetle-start.sh
  backend1:
    image: ghcr.io/lucasew/playground-rinha202401-backend
    restart: always
    environment:
      - "TB_ADDRESS=db:3000"
      - "GOMEMLIMIT=80MiB"
    build:
      dockerfile: ./Dockerfile.go-backend
    depends_on:
      - db
  backend2:
    image: ghcr.io/lucasew/playground-rinha202401-backend
    restart: always
    environment:
      - "TB_ADDRESS=db:3000"
      - "GOMEMLIMIT=80MiB"
    build:
      dockerfile: ./Dockerfile.go-backend
    depends_on:
      - db
