services:
  db:
    image: lucasew/rinha202401-tigerbeetle-db
    ports:
      - "3001:3000"
    build:
      dockerfile: ./Dockerfile.tigerbeetle
    deploy:
      # resources:
      #   limits:
      #     memory: 1024M
    volumes:
    - ./data:/data
