[tools]
atlas = "latest"
"github:sqlc-dev/sqlc" = "latest"
go = "latest"

[tasks."codegen:migrations"]
run = "atlas migrate diff init --to file://db/schema.sql --dev-url docker://postgres --dir file://db/migrations"

[tasks."codegen:queries"]
run = "sqlc generate"

[tasks.codegen]
depends = ["codegen:*"]

