[tools]
atlas = "latest"
"github:sqlc-dev/sqlc" = "latest"
go = "latest"

[tasks."codegen:migrations"]
run = "atlas migrate diff {{option(name=\"name\", required=True)}} --to file://db/schema.sql --dev-url docker://postgres --dir file://db/migrations"

[tasks."codegen:queries"]
run = "sqlc generate"

[tasks.codegen]
depends = ["codegen:*"]

[tasks."devdb:migrate"]
run = "atlas migrate apply --url 'postgres://admin:admin@localhost:5432/admin?sslmode=disable' --dir file://db/migrations"

[tasks."devdb:up"]
run = " docker run --rm -e POSTGRES_PASSWORD=admin -e POSTGRES_USER=admin -e POSTGRES_DATABASE=admin -d -p 5432:5432 postgres"

[tasks."dev"]
run = "go run main.go --db postgres://admin:admin@localhost:5432/admin"

[tasks."test:insert-user"]
run = "curl http://localhost:5090/create-user -F name={{option(name=\"user\", required=True)}}"
