name: payment

x-service-templates:
  api: &api
    networks:
      - backend
      - payment-processor
    build: .
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

services:
  redis:
    image: redis:8-alpine
    networks:
      - backend
  api1:
    <<: *api
  api2:
    <<: *api
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - backend
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
