export const lyrics = [
  "Quando eu digo que não quero mais você é porque eu te amo",
  "Quando eu digo que não quero mais você é porque eu te amo",
  "Eu tenho medo de te dar meu coração",
  "E você fazer o que bem entender",
  "Como se eu fosse um brinquedo pra você",
  "",
  "Eu já tentei, já fiz de tudo pra te esquecer",
  "Mas o meu coração não quer me obedecer",
  "E diz pra mim que não consegue viver sem você",
  "",
  "E nessa loucura de dizer que não te quero",
  "Vou negando as aparências, disfarçando as evidências",
  "Mas pra que viver fingindo se eu não posso enganar meu coração?",
  "Eu sei que te amo!",
  "",
  "Chega de mentiras, de negar o meu desejo",
  "Eu te quero mais que tudo, eu preciso do seu beijo",
  "Eu entrego a minha vida pra você fazer o que quiser de mim",
  "Só quero ouvir você dizer que sim!",
  "",
  "Diz que é verdade, que tem saudade",
  "Que ainda você pensa muito em mim",
  "Diz que é verdade, que tem saudade",
  "Que ainda você pensa muito em mim",
];
